name: Build and Release

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  debug-aws:
    name: Debug AWS Resources
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_DEV }}
          aws-region: us-east-1
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
      - name: Query Specific S3 Buckets
        env: 
          S3_BUCKET: ${{ secrets.DEV_CDN_S3_BUCKET }}
          S3_BUCKET_STAGING: ${{ secrets.DEV_STAGING_CDN_S3_BUCKET }}
        run: |
        
          echo "Querying DEV_CDN_S3_BUCKET..."
          command_dev=$(aws s3api head-bucket --bucket $S3_BUCKET || echo "Failed or Not Found")
          echo $command_dev
          
          echo "Querying DEV_STAGING_CDN_S3_BUCKET..."
          command_staging=$(aws s3api head-bucket --bucket $S3_BUCKET_STAGING || echo "Failed or Not Found")
          echo $command_staging
