name: Build and Release

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  debug-aws:
    name: Debug AWS Resources
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_DEV }}
          aws-region: us-east-1
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
      - name: Query Specific S3 Buckets
        run: |
          echo "Querying DEV_CDN_S3_BUCKET..."
          aws s3api head-bucket --bucket ${{ secrets.DEV_CDN_S3_BUCKET }} || echo "Failed or Not Found"
          
          echo "Querying DEV_STAGING_CDN_S3_BUCKET..."
          aws s3api head-bucket --bucket ${{ secrets.DEV_STAGING_CDN_S3_BUCKET }} || echo "Failed or Not Found"
      - name: Query Specific CloudFront Distributions
        run: |
          echo "Checking status of DEV_CDN_DISTRIBUTION_ID..."
          aws cloudfront get-distribution --id ${{ secrets.DEV_CDN_DISTRIBUTION_ID }} --query "Distribution.Status" --output text || echo "Failed or Not Found"
          
          echo "Checking status of DEV_STAGING_CDN_DISTRIBUTION_ID..."
          aws cloudfront get-distribution --id ${{ secrets.DEV_STAGING_CDN_DISTRIBUTION_ID }} --query "Distribution.Status" --output text || echo "Failed or Not Found"